class Config:
    THAW_SWARMS = False
    INITIAL_RANGE = 2000
    MAX_RANGE = 2000
    DROP_PROB_SENDER = 0
    DROP_PROB_RECEIVER = 0
    STATE_TIMEOUT = 0
    SIZE_QUERY_TIMEOUT = 10
    DEAD_RECKONING_ANGLE = 0
    CHALLENGE_PROB_DECAY = 5
    INITIAL_CHALLENGE_PROB = 1
    CHALLENGE_LEASE_DURATION = 1
    FAILURE_TIMEOUT = 60 * 2
    FAILURE_PROB = 0
    NUMBER_ROUND = 5
    ACCELERATION = 1
    DECELERATION = 1
    MAX_SPEED = 3
    DISPLAY_CELL_SIZE = 0.05
    HD_TIMOUT = 5
    SIZE_QUERY_PARTICIPATION_PERCENT = 1
    DECENTRALIZED_SWARM_SIZE = False
    CENTRALIZED_SWARM_SIZE = False
    PROBABILISTIC_ROUND = False
    CENTRALIZED_ROUND = True
    BUSY_WAITING = False
    MIN_ADJUSTMENT = 0
    SAMPLE_SIZE = 0
    DURATION = 60 * 1
    READ_FROM_NPY = 0
    K = 5
    H = 2
    MAX_NEIGHBORS = 0
    SHAPE = 'racecar'
    RESULTS_PATH = '/proj/nova-PG0/hamed/results'
    DEBUG = False
    FILE_NAME_KEYS = ['DISPATCHERS']
    DIR_KEYS = ['H']
    SERVER_TIMEOUT = 120
    PROCESS_JOIN_TIMEOUT = 120
    DISPATCHERS = 5  # valid values 1 3 5
    DISPATCH_RATE = 1  # valid values 'inf' or a non-zero number
    C = 1  # number of standbys per group valid values are 0 and 1
    MULTICAST = True
    INPUT = 'racecar_K:5'
